### PR TITLE
Added ability to use unsigned data in Intensity Graph

### PR DESCRIPTION
**Pull request by mfurseman**
This adds the functionality to use unsigned data types as the input data to the Intensity Graph.

### CODE REVIEW

**Comment by PeterC-DLS** [comment]
Can the converter be more conservative with regard to memory usage? I.e. promote to the next wider primitive type rather than use doubles unconditionally?

**Comment by mfurseman** [comment]
This seems possible, however it would also require changing the cropDataArray function for it to be really useful. The only implementation I can currently think of would be to change the IPrimaryArrayWrapper to expose a set method (taking a double and downcasting), or to copy and paste the code in the cropDataArray and  convertFromUnsignedArray functions for each different data type.

**Comment by PeterC-DLS** [comment]
You could use in a delegate class (``UnsignedPrimitiveArrayWrapper``) that overrides the get method and so save creating an array in the first place.

**Comment by mfurseman** [comment]
@PeterC-DLS  I've added a commit that uses a delegate class instead of the conversion function.

**Comment by PeterC-DLS** [comment]
Nice!

**Pull request merged**
